TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: -0.3
  acc_lim_x: 2.0
  acc_lim_theta: 2.0
  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

