obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.1, 0.06], [0.1, -0.06], [-0.1, -0.06], [-0.1, 0.06]]
inflation_radius: 0.1
cost_scaling_factor: 10.0

observation_sources: scan

scan: {
  sensor_frame: laser,
  data_type: LaserScan,
  topic: /scan,
  marking: true,
  clearing: true,
  expected_update_rate: 0.2
}
